language: php

php:
    - 5.4
    - 5.5
    - 5.6
before_script:
    - phpenv rehash
    - composer install --dev
script:
    - find ./src/ -name "*.php" -exec php -l {} \; && \
      vendor/bin/phpcs --standard=PSR2 --report=full src && \
      phpunit --configuration phpunit.xml --stderr      
